/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 RocketShip.glb -T -S 
Files: RocketShip.glb [1.18MB] > D:\S7\Webcup2024\webcup2024\front\public\models\RocketShip-transformed.glb [75.18KB] (94%)
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function RocketShip(props) {
  const { nodes, materials } = useGLTF("/models/RocketShip.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Node.geometry}
        material={materials.PaletteMaterial001}
      />
    </group>
  );
}

useGLTF.preload("/models/RocketShip.glb");
